import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box, chakra } from "@chakra-ui/react";
import { ColorModeButton } from "../components/color-mode-button";
import { Header } from "../components/header/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ColorModeButton />
    </>
  );
}

export { getServerSideProps } from "../components/chakra";
